### ISSUE TITLE
Make gaucho work as an npm global package

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#101]
installing gaucho as a global package with (`npm install -g gaucho`) should allow to execute gaucho using `gaucho` using the package https://www.npmjs.com/package/gaucho

**Comment by angrykoala** [comment]
Upload a distribution version (probably require it's own separate build) to npm

**Comment by rkomiyama** [comment]
Getting the following error:

`npm ERR! path /usr/local/lib/node_modules/gaucho/electron .
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/gaucho/electron .'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent `

**Comment by angrykoala** [comment]
yeah, I still don't know how to fix that tbh, there may be some docs related to how to install globally an electron app. Anyway this is a very low importance issue for now

**Comment by angrykoala** [comment]
This won't be really necessary unless a cli version is developed, gaucho can run if the package is installed anyway
