### ISSUE TITLE
Graphical automated tests

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#105]
Try using nightmare.js (or something similar) to add UI tests to the unit tests

**Comment by rkomiyama** [comment]
I'll take this up to allow testing for #216.

**Comment by angrykoala** [comment]
Perfect, thanks. please, tell me what are you planning to use for this?

**Comment by rkomiyama** [comment]
I was thinking of using [Nightwatch.js](http://nightwatchjs.org/).

**Comment by angrykoala** [comment]
Ok, looks good, I never tried it.
Please, make sure to check [Nightmare.js](http://www.nightmarejs.org/) before deciding on the tooling

**Comment by rkomiyama** [comment]
I haven't used Nightmare.js before, so I'm willing to try it out.

**Comment by angrykoala** [comment]
I don't know which is better tbh, I would like you to read a bit on nightmare to decide which is a best option. I'm just suggesting nightmare because I used it a couple of times and it has more stars in GH, but nightwatch looks good too, so I'm not sure of the pro/cons

**Comment by rkomiyama** [comment]
Is there a way to access the project via `localhost`?

**Comment by angrykoala** [comment]
Sorry, I don't understand.

The project is launched with its own instance of browser using electron. In order to create tests we should probably launch electron along with the tests. I'm afraid I'm not sure how to integrate a web automation tool with electron, but it is quite a common case so it shouldn't be hard to find documentation related to that or some library.

**Comment by angrykoala** [comment]
As @rkomiyama found, [Spectron](https://github.com/electron/spectron) looks like the appropriate tool for this
