### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#11]
A nice mate would make a good icon

**Comment by angrykoala** [comment]
Icon should be added to the build process

**Comment by aebsubis** [comment]
Font used: Brush Script Std Medium
![High res icon](https://cloud.githubusercontent.com/assets/2852139/22181970/83a319ac-e090-11e6-840c-0223a54ca0f0.png)
[All source files](https://github.com/angrykoala/gaucho/files/721875/GauchoIcon.zip)

**Comment by angrykoala** [comment]
This image will then be added to the repository under a CC-by-sa license under the name "Gaucho Logo" and @aebsubis as author

**Comment by angrykoala** [comment]
With an icon 128X128 it seems to work in ubuntu (check https://github.com/electron/electron/issues/6205)

**Comment by angrykoala** [comment]
Added icon, tested on:
- [x] Ubuntu
- [ ] Windows
- [ ] Other Linux
- [ ] Mac

Currently, on Ubunut only icon.png with 128x128 pixels work. Probably some changes should be made for mac

**Comment by angrykoala** [comment]
This issue will be closed after testing in windows, potentially a new iccue should be specifically created for mac
