### ISSUE TITLE
First time welcome message

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#138]
A welcome message the first time gaucho is executed, with some links and instructions maybe

**Comment by angrykoala** [comment]
A similar modal as used in about can be used for this.

Check if a generic component could be used for both thins

**Comment by panvourtsis** [comment]
will work on this as well because its relevant to #147 

Do you have a message in mind?

**Comment by angrykoala** [comment]
Not really, I was thinking on a popup, similar to the about popup, but a bit more friendly. This could be used along with the feature discovery described in #147 as a "tutorial" or "learning" process at the beginning, or maybe with just one of those is enough

**Comment by panvourtsis** [comment]
i guess we can introduce two popups rather than a welcome. One on the edit as we discussed at #147 and after some time one on the menu. Just like an introductory wizard

**Comment by angrykoala** [comment]
Wouldn't it be a bit annoying to have so many popups?
Do the menu requires a popup also? I mean... is right next to the other button...

If you think it needs one, could the same popup used for both?

**Comment by panvourtsis** [comment]
You might be right but on the other hand i dont think welcome message is mandatory as well. I guess the popup only on edit is enough

**Comment by angrykoala** [comment]
Ok, I guess you are right, the welcome message was just an idea to provide some information in a friendly way. I'm ok with only having the popup as a first-time message (regardless on other conditions)

If you agree, I'll close this issue as a "wontfix"

**Comment by panvourtsis** [comment]
yup, will stick on the other task then ;)

**Comment by angrykoala** [comment]
Wontfix, related to #147
