### ISSUE TITLE
introduce pre commit functionality

### ISSUE THREAD

**Issue by panvourtsis** [angrykoala/gaucho#145]
Can we have a pre commit functionality to run necessary procedures like jshint for example before letting anyone commit. I found this very useful

**Comment by angrykoala** [comment]
Wouldn't it be a hassle to run all those checks with every commit?, I only care of having everything right at the moment of creating a pull request and all checks can be done with `npm test` (including jshint).

Anyway, I'm ok with adding the pre-commit script pointing to npm test to see how it works

**Comment by panvourtsis** [comment]
avoiding though any additional commits to fix the jshinting etc. will create a pr later in the day for you to see

**Comment by angrykoala** [comment]
@panvourtsis could you describe how to make the pre-commit functionality work? after fresh clone and `npm install`, the pre-hooks are still the default ones and no checks are done before commit

**Comment by panvourtsis** [comment]
hi @angrykoala i just checked it on a new branch and is all good. Maybe the pre-commit wasnt installed?

**Comment by angrykoala** [comment]
Have you tried from a fresh clone? tbh I'm not sure how hooks work. `npm install` installed the pre-commit package, but it seems to ignore the actual hook setup

**Comment by panvourtsis** [comment]
yes i did try from a fresh clone. Actually my test is as follows

1. clone
2. checkout to the dev
3. change the task.js by adding a second semicolon so the jshint to got an error
4. trying to commit

you can try an error on the tests as well you can see that it will not commit it.

**Comment by angrykoala** [comment]
Thanks for the specific steps, I'll try it as soon as I can, and come back to you with the result

**Comment by angrykoala** [comment]
Indeed, it seems to be working fine, probably a mees-up with my env. I'll close this issue then
Thanks
