### ISSUE TITLE
Investigate the use of feature discovery on the edit button

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#147]
The materliazecss feature discovery (http://materializecss.com/feature-discovery.html) could be use to point to the edit button if there are no tasks

**Comment by panvourtsis** [comment]
hey, i am working on this. 

Couple of questions. Do you have in mind to popup such message on each refresh or open of the application and when the edit closes with no tasks ?

**Comment by angrykoala** [comment]
Mmm, my idea was to show the popup when the application is **not** in edit mode for a few seconds and the user may not know how that works.

So, maybe we can show it when the following conditions are met:
* The _edit mode_ is **not** active for a few seconds
* The suites are empty
* The edit mode wasn't activated in the session (session = app started)
* The popup wasn't activated in the session

What do you think about those conditions? This task is also a bit of investigation, as I'm not sure if the popup is a good design decision or not.

Also, now it comes to my mind that a simple message in the place where the tasks should be could also be useful (either replacing or along with the feature discovery). Something like "To start adding tasks, press the edit button (<show the edit icon>)

Again I'm not sure if these are good or bad design choices, so I would like to know your opinion

Thanks for taking this issue

**Comment by panvourtsis** [comment]
These conditions were what i was thinking too. But again is a bit annoying to have a popup every time you open the application with no tasks ... Although the popup has a better ui animations i think its more proper to show only a message. Check an image with a demo i made with the popup
<img width="1186" alt="screen shot 2017-10-04 at 12 39 06" src="https://user-images.githubusercontent.com/6433679/31169376-141d3c86-a901-11e7-8793-0392d6bab53f.png">

**Comment by angrykoala** [comment]
Looks good.

Yeah, you are right about the annoying popup. What about adding a plain grey-ish message and having the popup to show only the first time the app is opened? Would that make sense or maybe with the message is enough?.


btw, this idea of one time popup is related to #138

**Comment by panvourtsis** [comment]
yes i've seen it. i agree with this.

**Comment by panvourtsis** [comment]
a question, how do you accomplish first time visit. I though about localStorage value

**Comment by angrykoala** [comment]
We do not need localStorage value, as in electron we can access permanent disk storage.

We are using the module [electron-store](https://github.com/sindresorhus/electron-store) to simplify the configuration storage. You can check the interface to access gaucho config [here](https://github.com/angrykoala/gaucho/blob/master/app/common/app_config.js)

Basically, adding a flag (e.g. "firstTime" set to true) in the config and changing it when the popup is displayed should do the trick.

**Comment by angrykoala** [comment]
Even, by simply checking if a config already exists we could actually check if it's the first time without having to store anything
