### ISSUE TITLE
Confirmation on delete

### ISSUE THREAD

**Issue by panvourtsis** [angrykoala/gaucho#148]
Need a popup or something to confirm a deletion on a task

**Comment by angrykoala** [comment]
ditto for suite deletion, and config/clear tasks

A generic popup with confirmation component would be useful to be used on all of these cases.

**Comment by wildan3105** [comment]
Hi, I'd love to work on this. Do you give me a shot?

**Comment by angrykoala** [comment]
Hi @wildan3105, thanks for reaching out. This issue was created by @panvourtsis, so he should decide if he wants to work on this or let you do it.

Meantime, feel free to check all the other issues (or open your own) and work with whatever you prefer

**Comment by panvourtsis** [comment]
hi @wildan3105, please feel free to work on this

**Comment by panvourtsis** [comment]
@wildan3105 are you working on this ?

**Comment by wildan3105** [comment]
Sorry, I had other work to do. You can do by yourself @panvourtsis :disappointed:

**Comment by panvourtsis** [comment]
just checking ! will do after i finish another task. Will let everyone know here

**Comment by angrykoala** [comment]
@wildan3105 If you want to work on this at some point before @panvourtsis starts it, or in any other task/idea whenever you can, feel free to do it :)

**Comment by panvourtsis** [comment]
i made a custom component for modals that we could pass and id title and desciption in order to render. The problem is with materializecss that we need to pre render each of this components in order for it to show them.

Shall we use sweetalert which has a cool integration with vuejs ? https://limonte.github.io/sweetalert2/

**Comment by angrykoala** [comment]
I think there are ways to simplify the problem you say (I basically wrap everything in materialize.js)

I would usually say of fixing stuff instead of adding a new library. But to be honest that library looks great (I didn't know it)

Just a couple of questions:
* Could use that library for every modal (the about menu we currently have)?
* If no, would it make sense to have 2 different styles, one for confirmation using sweetalert and other for other modals?

**Comment by panvourtsis** [comment]
I was suggesting to have every modal on this library 

> this will help us not having "junk" html on the code 

One library would help us fix the current implementation but will also help show messages on the future

**Comment by angrykoala** [comment]
I simply ask about more complex modals (such an about menu or potentially something with a form).

If you think it won't be a problem, go for it, just keep in mind that the about menu should be changed to use this library as well

**Comment by panvourtsis** [comment]
It would easily handle such things. If we agree on this i would change all these modals

**Comment by angrykoala** [comment]
Seems fine by me, just to be sure, you can just add one modal so we can confirm how it works so I (or whoever else that wants) could test it live to make sure everything is ok, but for what I saw in the web those seems to be quite nice and along with the general style of gaucho

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
