### ISSUE TITLE
Provide a temporal config for development

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#155]
Because now config is stored globally, when trying things in dev, you own gaucho config may be affected.

Maybe with a DEV flag or something it would be possible to connect to a different storage than the plain gaucho storage

**Comment by tdeschryver** [comment]
OK if I take this one? :smile:

**Comment by angrykoala** [comment]
@tdeschryver Sure, keep in mind that we may need to do some changes in the build process to provide the properenv variables

**Comment by angrykoala** [comment]
@tdeschryver Sorry, I didn't notice you solution in #159 is incomplete.

It seems to be working fine for the config, however, the exact same behaviour should be implemented for the tasks as well (Store in `app/renderer/task_config.js`) so the tasks are also working in a separate config environment.

Sorry, the issue was not properly described here. Would you mind adding those changes to a new PR? It should be trivial.

In the future, those stores should be implemented on a separate class, to avoid having to make changes in 2 random places,I'll create a new issue for this

**Comment by tdeschryver** [comment]
I thought that would be the desired behavior but forgot to ask. I'm on it!
