### ISSUE TITLE
Task ordering improvements

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#156]
The ordering defined and implemented in #87 and #153 can be improve, fixing the following minor issues

- [x] When starting a drag **all** the tasks should be closed (the edition menu) as it makes harder to actually reorder:
- [x] The "drag" behavior is still active when not on edit mode (you cannot actually change the tasks order, but the cards are draggable, this should be trival to solve, adding a class to avoid this when not in edit mode 

- [ ] The tasks "jump" when reordering sometimes (sorry, I cannot make a screenshot of this) I'm not sure if this is easy or hard to solve, as I feel it is caused by "removing & adding" a task on drag. It may even be because of the library

* ~~When reordering a running task, the log will remain in the previous position~~ Check #213 
![screenshot from 2017-10-08 22-38-15](https://user-images.githubusercontent.com/5960567/31320719-7b097b96-ac79-11e7-8544-281d7507d088.png)
As you can see, the only running task (redis) is showing the log in the previous position. This problem is confirmed to happen when deleting a task above the running task as well, so it'll probably require some extra implementation, as it is not exclusive of task reordering

- [x] Reordering should only work when dragging in the task card (name and drag icon), not when dragging in the form. This makes impossible to copy the text in the form nor in the run button

**Comment by panvourtsis** [comment]
i am on it !

**Comment by angrykoala** [comment]
Hi @panvourtsis because this task is quite big, if you need some help with it just write a comment here.
Keep in mind that I'm happy to accept a PR with any of the fixes, no need to solve all of them in one go
