### ISSUE TITLE
Code style and linting

### ISSUE THREAD

**Issue by panvourtsis** [angrykoala/gaucho#161]
Hi again. Using the repository for a while i think that the jshint isnt fiting exactly the needs with vue and electron.
It is lacking the code style and the jsx support. I was using my self the jslint from douglas crockford but i think for this repository the best fit would be js standard.
Has jsx support and a great command --fix which crawls all you code and fix it automatically to the rules from js standard. So i am suggesting switching to it.

https://standardjs.com

Let me know your thoughts

**Comment by angrykoala** [comment]
I though for a while on changing to [eslin](https://eslint.org/) as I though is the de-facto standard linter currently.
I'm ok with changing the linter to whatever and adding an automatic fix method, however, keep in mind a few things:
* We do not need jsx support afaik, at some point I want to move the vue.js components to single-page-components #116 which would allow proper linting/beautification on those (I'm not sure what do we need to get linting on those files)
* I've seen standard.js and there are a few things that I don't like about its default configuration (I assume it can be changed)  like no semicolons or using single quotes for strings (tbh I don't thing standard.js actually represents the standard way of coding javaScript)

So, imo, I would prefer going with eslint, as the main point of using standard.js is not having a file, but if we do not want the default config, we need a .eslint anyway. About automatic fixing, I usually use `jsbeautify` and I'm not sure eslint provides this feature, so there may be a point of using standard.js with .eslint file to get the --fix option.

These are all my thoughts on this issue, feel free to try and change to the one you think is the best, just make sure the rules are configurable

**Comment by panvourtsis** [comment]
I see your points.
StandardJS its just the name doesnt mean is the standard format of the js. Sadly there is no standard formating that is why we all try these tools. 

I used eslint in the past but i prefer opinionated tools without configuration like jslint and standarJS. For the semicolons there is a fix but for all the others there is none.

I havent used standardjs with eslint so i guess it might have that options but not sure either.

**Comment by angrykoala** [comment]
```
StandardJS its just the name doesnt mean is the standard format of the js. Sadly there is no standard formating that is why we all try these tools.
```
Yes, I know, just pointing out the irony :laughing: 

```
I used eslint in the past but i prefer opinionated tools without configuration like jslint and standarJS. For the semicolons there is a fix but for all the others there is none.
```
That's a [shame](http://i0.kym-cdn.com/photos/images/newsfeed/000/956/638/5bc.gif). I agree on using opinionated tools as those are simpler, but like in any good democracy I like things with the same opinion as me </joke>

Any thoughts on eslint? In the end, we are already using a config file for jshint, so it is not like we are losing anything. Oh, **I forgot to check jslint**, I like this style better,  why do you think standard is better for this project?

I'm ok with giving a try to jslint and check if, by default, has a similar style that the one we are using here. If not, I'm ok with using a tool with a .whatever config file

Up to you on what to use, I don't want to enforce the tooling we use, except for a few little things in code :)

**Comment by panvourtsis** [comment]
i am on it just to avoid any confusion 😆
