### ISSUE TITLE
The "Edit tasks" popup should appear, even if there are already tasks

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#166]
Because gaucho provides default tasks, even if the suite is not empty, the popup (#158 #147) should appear when first used.

**Comment by angrykoala** [comment]
This issue should be quite easy for first-time contributors

**Comment by Hrafnkellos** [comment]
I'll have a look

**Comment by AhsanAyaz** [comment]
@angrykoala can you give some context on this one? 
I've seen the previous implementation and I see that the popup opens on first use. 
What is the intended vs current behaviour?

**Comment by angrykoala** [comment]
@AhsanAyaz Sorry, you are right, I was under the impression (probably due to an older version) that the popup was only triggered when there were no tasks in the suite. 

My bad for testing it wrong. I can confirm that it is working as intended, so this issue is no longer relevant. @Hrafnkellos
