### ISSUE TITLE
Setting an infinite task will block every interaction

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#168]
A task such as `yes yes` will completely block gaucho

**Comment by ccalamos** [comment]
Would a possible timeout setting which then displays it as an error be possible work around?

**Comment by angrykoala** [comment]
Not really, the problem is not an infine executing task (such a server) but a task consuming infinite resources (such an infinite loop doing calculations)

Im still not sure why this happens or under which conditions, in theory new tasks should be executed on new processes and shouldn block any interactions with gaucho (unless the computer is completely blocked, which wasnt the case). This issue may have something to do with the task runner (yerbamate) not spawning children processes properly, im not sure tbh

**Comment by angrykoala** [comment]
After 0.5, a command such as `yes yes` doesn't affect performance while its working, but it completely blocks gaucho if stopped

**Comment by angrykoala** [comment]
the command `yes yes` shows the following error in the console:
```
/home/angrykoala/Git/gaucho/node_modules/yerbamate/app/runner.js:48 Uncaught RangeError: Invalid string length
    at Socket.proc.stdout.on (/home/angrykoala/Git/gaucho/node_modules/yerbamate/app/runner.js:48)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at addChunk (_stream_readable.js:263)
    at readableAddChunk (_stream_readable.js:250)
    at Socket.Readable.push (_stream_readable.js:208)
    at Pipe.onread (net.js:594)
```

this issue may be related to yerbamate, and not gaucho

**Comment by angrykoala** [comment]
Other tasks such as while :
```
do
	echo "Press [CTRL+C] to stop.."
	sleep 1
done
```
won't break anythin

**Comment by angrykoala** [comment]
Issue happening with any infinite task that is logging to the screen, the problem is that yerbamate stores the whole log, until there is not enough memory.
This requires a fix in yerbamate, setting an option to limit the size of the log

**Comment by angrykoala** [comment]
Yerbamate 2.1.0 has an option to set a maximum output in the task, this should fix the problem
