### ISSUE TITLE
Pre-commit hook only on certain branches

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#170]
Is it possible to setup the pre-commit #145  hook only in certain branches (or skip some)?. This is because the hook is active for gh-pages branch, where it doesn't makes sense @panvourtsis

**Comment by panvourtsis** [comment]
sadly the pre-commit library doesn't have such a restriction. But in your case that branch is a seperate project actually. You don't have a package.json. You don't have to put it there.

**Comment by angrykoala** [comment]
Yes, it is a separate project (which has to be in the same repo as is a github page), and I don't have package.json or anything there, but because the hooks are installed in the `.git` folder, when checking to that branch, the hooks are still active.

It is not a big deal, but the warning is annoying

**Comment by angrykoala** [comment]
I opened an issue on pre-commit library (https://github.com/observing/pre-commit/issues/114) to see if they are interested in adding this feature.

I'll close this issue for now
