### ISSUE TITLE
Improve overall style of sweetalert

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#173]
Alerts using sweetalert can be slightly improved:

* ~~Remove tab indicatorsin buttons~~
![screenshot from 2017-10-09 16-15-40](https://user-images.githubusercontent.com/5960567/31342502-4558a514-ad0d-11e7-9c19-3f6778843079.png)
* Make text non-selectable in modals
* Don't change the pointer to a hand when hovering in a clickable element (this, while common in webs, is not common in desktop apps)

**Comment by PhilTerz** [comment]
I'd like to go ahead and work on this.

However, I think there are Accessibility concerns with the first. Removing tab indicators can have detrimental effects on keyboard users that rely on those focus indicators.

**Comment by angrykoala** [comment]
yes, you are right, But in order to actually improve accessibility we would have to make a style and rules constant to all the app, I'll create a explicit issue for this related to the whole app.

Generally, there are no "default highlight" in a desktop app, in fact, it is overlaid only when an user press tab. The best solution, in fact, would be to remove the default selection, so if the user press tab, the first button is highlighted (using the same style is now being used)

Thought on this @PhilTerz ?

**Comment by angrykoala** [comment]
New issue according to what we discussed @PhilTerz

**Comment by PhilTerz** [comment]
Yes, I agree. Your new issue details all aspects of the problem well!

**Comment by angrykoala** [comment]
Most of these problems are solved
