### ISSUE TITLE
Close "Add Task" from when task saved

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#181]
Saving a new task will leave the "Add Task" form open to add a new task. This behavior is a bit inconsistent. Is better to completely close the form, the same way it works when editing a  task

**Comment by DefecateRainbows** [comment]
I'll try this out.

**Comment by DefecateRainbows** [comment]
It's going to take me 8+ hours to get back to this, if someone else wants to do it in that time, that's fine by me

**Comment by panvourtsis** [comment]
i could do it if you want

**Comment by angrykoala** [comment]
Aren't you already in 2 or 3 other issues @panvourtsis ?

**Comment by panvourtsis** [comment]
only task ordering which is very close to this. #156

**Comment by angrykoala** [comment]
If I remember correctly, you also offered to do #161 
I mean, you can work on whatever you want, and it's ok by me if you want to do this issue, but if you are going to take a break from an issue (to work on another thing or simply because of lack of time) send a message so other people are aware and can work on that thing.

Mainly to avoid blockings or people working on the same thing :smile:

**Comment by panvourtsis** [comment]
Yeah we discussed #161 but i didn't know you expected i'll do it. Go confused there!
I will though thanks for clarifying ;)

**Comment by angrykoala** [comment]
Oh, sorry, I misunderstood about #161 .

**Comment by DefecateRainbows** [comment]
Alright, I'm on this.

**Comment by DefecateRainbows** [comment]
Alright, I'm having much more trouble than I should with this. Someone else is going to have to do this D:

**Comment by ssteuteville** [comment]
I'll try tonight.

**Comment by ssteuteville** [comment]
hmmmm.. I have this implemented but I can't get the tests running on Windows 10. Any advice?

`$ npm test

> gaucho@0.3.0 test C:\Users\ssteu\dev\gaucho
> npm run clean && istanbul cover _mocha && npm run jshint


> gaucho@0.3.0 clean C:\Users\ssteu\dev\gaucho
> rm -rf builds config.json tasks.json coverage

No coverage information was collected, exit without writing coverage information
C:\Users\ssteu\dev\gaucho\node_modules\.bin\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\ssteu\dev\gaucho\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at runFn (C:\Users\ssteu\dev\gaucho\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
npm ERR! Test failed.  See above for more details.`

**Comment by angrykoala** [comment]
@ssteuteville Try to execute just `mocha`

Please, tell me the result of `node -v` as well

**Comment by ssteuteville** [comment]
I got it working with the command listed in this issue. https://github.com/gotwarlost/istanbul/issues/90

node -v v6.11.1

**Comment by angrykoala** [comment]
I'll add this problem to a page in the wiki, in case someone else has this issue with the tests
