### ISSUE TITLE
Minor code improvements

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#186]
There are minor improvements to perform in the code overall (or things that should be checked):

- [x] app/renderer/suite.js line 64: Extract the string inside existTaskName to a separate variable with a proper name
- [x] main.js line 16: Instead of parsing a string, check if the url module can be used
- [x]  app/renderer/suite.js line 61: `let` used instead of `const`. Check if there is a reason for this

> Lines may be aproximate

**Comment by kushalpandya** [comment]
I can take this up. :slightly_smiling_face:

**Comment by angrykoala** [comment]
Any other improvement you can see, is welcome as well
