### ISSUE TITLE
Add confirmation alert for 'clear tasks' action

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#188]
Use the same alert wrapper as suite and task delete

**Comment by ccalamos** [comment]
Do you mean when deleting a task?

**Comment by angrykoala** [comment]
No, that already exists, when entering conguration, you have the action of "clear all tasks". That should have a similar alert/modal than the current modal displayed when deleting a task or suite (to check this, make sure you are on dev branch and updated)

**Comment by ccalamos** [comment]
I can replicate the same modal as requested, however there are some errors within clearing tasks itself that should be addressed as well such as the ticker not decreasing to zero.

**Comment by angrykoala** [comment]
What ticker? You mean the tasks list? That should be fixed, make sure you are running latest `dev` branch, if the problem persist, please, open a new issue detailing the problem and how to replicate

Also, replicating the modal should be trivial, as our current wrapper already does that for you, so basically is running that wrapper before executing the action of the button. Do you want to do it @ccalamos ?

**Comment by techpool** [comment]
Hi @angrykoala, I would like to take up this task and proceed with it. Can you point out the location where I should start looking into?

**Comment by angrykoala** [comment]
Sure @techpool , the code to display alerts is in `app/renderer/app_alerts` you shouldn't even need to modify it, but in case you need to, it should be easy to extend and export a new class from AppAlert, the `DeleteConfirmationAlert` however should be enough for this issue.

In `app/renderer/components/config_menu.js` you have the component of the config menu where you can find the `clear task` button action.

Remember to checkout to `dev` branch before working on this

**Comment by angrykoala** [comment]
@ccalamos Maybe the problem you reported is the same as #190 ? If so, it should be already fixed

**Comment by grg121** [comment]
HI, @ccalamos @techpool Are you still working on this?

**Comment by ccalamos** [comment]
@grg121 Sorry I was away from my computer this weekend, @angrykoala yes it is the same as issue #190 and I can do this by tonight however I do not want step on @techpool's feet if he is currently working on this. If not I would like to claim it and submit a PR by tonight.

**Comment by techpool** [comment]
Same here @grg121. @ccalamos you can go ahead and create the PR. I'm not sure if I'll be able to make it my tonight. Thanks.

**Comment by angrykoala** [comment]
Ok, so @ccalamos will work on this, thanks @techpool and @grg121
