### ISSUE TITLE
When using Tab on command in task form, an error is raised

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#200]
The following error is reised when using tab on `command` field in a task form
![screenshot from 2017-10-15 23-11-43](https://user-images.githubusercontent.com/5960567/31589217-4e1fc97a-b1fe-11e7-8cfd-3ff3f03953c3.png)

Probably caused by #179, doesn't seem to affect usability, but we need to get rid of that message and investigate why it is happening

**Comment by angrykoala** [comment]
To reproduce, imply tab all form inputs

**Comment by Trevormichael** [comment]
I got this one
