### ISSUE TITLE
Config menu should close when confirming clear task

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#203]
Only when confirming, not before or when canceling
Related to #188

**Comment by ccalamos** [comment]
Quick question on this... Your eslint does not include jQuery definitions, I can change it in this PR to do so, however the easiest way to perform this will require me to use the '$' which will throw a un-def error because you have not selected jQuery

**Comment by angrykoala** [comment]
You can use /* globals $ */ or something similar I think
