### ISSUE TITLE
Import task option

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#21]
Add an option to import a gtask.json file.

Importing the file will (for now) override the current suites and tasks, so an alert ( #162 ) should be used to let the user know and confirm if that's what he wants.

> Remember to stop **all** executing tasks when doing this, as they will be removed, this must be done **after** the user confirmed the alert

**Comment by angrykoala** [comment]
currently using tasks.json, investigate changing the filename to gtask.json

**Comment by angrykoala** [comment]
Changed issue name

**Comment by angrykoala** [comment]
Because export is already implemented (#23 #150 ) this issue is important for the following release (we need an import for the export). Do you want to take this issue @grg121 ?

**Comment by grg121** [comment]
yep, it's mine

**Comment by ssteuteville** [comment]
mb put wrong issue number on my pull request.. I'm not working on this.
