### ISSUE TITLE
Broken sinon dependency

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#210]
It seems that sinon has a broken dependency, investigate and fix it

**Comment by jhdoak** [comment]
This is a known sinon issue, related to a dependency three levels deep (just-extend) - [see here](https://github.com/sinonjs/sinon/issues/1591).

Temporary fix is to run npm install, remove just-extend, and explicitly install just-extend version 1.1.22.

```
npm install && rm -rf node_modules/just-extend/ && npm install just-extend@1.1.22
```

**Comment by angrykoala** [comment]
if the problem persist we could explicitly install just extend 1.1.22 in package.json

**Comment by jhdoak** [comment]
There is already an open issue in the sinon repo, but considering it's a dependency three levels deep it could take some time.

Until then, we could explicitly install just-extend 1.1.22 as you mentioned. I've actually got that change as a part of my fix for https://github.com/angrykoala/gaucho/issues/209. Should I include the change to package.json in my commits/PR for that issue?

**Comment by angrykoala** [comment]
Yeah, fine by me to include that change

**Comment by jhdoak** [comment]
This seems to be fixed according to comments from angus-c, just-extend collaborator (https://github.com/sinonjs/sinon/issues/1591). I got rid of the explicit version, ran an npm install, and successfully ran tests.

**Comment by angrykoala** [comment]
Did you removed the node_modules as well? If so, I'll remove this issue shortly

**Comment by jhdoak** [comment]
I did. I also deleted and re-cloned the project to verify. I'd encourage you to test it yourself to be sure, but things look good on my end.
