### ISSUE TITLE
When deleting a task or reordering, the log is not updated

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#213]
When reordering tasks or deleting a task, the log position is not updated and it will still be displayed in the old position. Related to #156

**Comment by panvourtsis** [comment]
Hi @angrykoala, what do you mean with this ?

**Comment by angrykoala** [comment]
Let's imagine 2 tasks in a suite (`echo 'hello'` as first task and `ls` as second) If you execute both, you will see the logs of each one by clicking in the card.
If you now swap them and open the log, the `hello` log will still be in the top card

**Comment by panvourtsis** [comment]
ok i will work on this. Will check and let you know
