### ISSUE TITLE
Tooltip with task status when hovering on status icon

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#216]
When hovering on the status icon on a task card, a tooltip could appear to make easier to understand its meaning:
* idle (black)
* running (blue)
* successful (green)
* failed (red)

**Comment by rkomiyama** [comment]
I'd like to be assigned this issue.

**Comment by angrykoala** [comment]
Consider it yours @rkomiyama 
Thanks taking interest in this project

**Comment by rkomiyama** [comment]
I have the implementation done. I believe all I have left is creating test case(s).

@angrykoala Do you have a preference as to where the test case should be? I was thinking about putting it in `task.test.js`.

**Comment by angrykoala** [comment]
snapshots?
eed 
Mmm, it depends on how are you focusing your tests. If the tests are only testin the Javascript part you can do them just the same way we do all the tests. If you want to test the html/css result you may need to use some tool such as Phantomjs, which we want to integrate as defined in #105
