### ISSUE TITLE
Make timers optional

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#218]
Add an option to config so the timers are displayed or not

If the timers are disabled, check if the performance can be improved by removing unnecessary events.
If the timers are enabled, the timers **must** have the correct values

**Comment by angrykoala** [comment]
![screenshot from 2017-10-25 15-52-29](https://user-images.githubusercontent.com/5960567/32002322-86b53392-b99c-11e7-940b-68b43b66898a.png)

**Comment by angrykoala** [comment]
![screenshot from 2017-10-25 15-52-54](https://user-images.githubusercontent.com/5960567/32002341-95ee3ab6-b99c-11e7-8071-22a4d95aef73.png)
_Example of timers_

**Comment by theTechie** [comment]
on it
