### ISSUE TITLE
Adding keyboard shortcuts

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#219]
Would it make sense to have keyboard shortcuts in gaucho? Either pre-defined shortcuts to move and execute tasks or configurable keys

**Comment by davidsonsns** [comment]
I believe key shortcuts can be a very interesting feature. Makes use much more convenient and fast.
If you agree, I'll start this feature.

You can attribute to me :smile:

**Comment by angrykoala** [comment]
Feel free to start with it. I recommend doing something simple, so we all can test it and see if it is working fine

Keep in mind that this may not be trivial to implement (depends on how electron and vue handle those kind of things)

**Comment by davidsonsns** [comment]
Great, I'll do it.
