### ISSUE TITLE
Distribute Gaucho in a PPA

### ISSUE THREAD

**Issue by JuanjoSalvador** [angrykoala/gaucho#223]
I can package gaucho into a `.deb` package just to install it using APT on Debian-based distributions (such as Debian, Ubuntu, ElementaryOS, Linux Mint, etc).

I have a ready PPA repository waiting for Gaucho 0.4.

I can maintain it too.

**Comment by angrykoala** [comment]
Gaucho is already built into a `.deb` package in the 0.4 version, you don't need to package it. 

Uploading to a PPA is a great idea, I'll check on that

**Comment by JuanjoSalvador** [comment]
Launchpad PPA doesn't allow to upload a `.deb` file, so we need to upload a `source.changes` file and then wait for Launchpad to make the `.deb` file. This is a problem considering Gaucho is an Electron app. Atom has its own PPA repository, so it is possible to make but I guess it's a bit complicated... Working on it.

**Comment by angrykoala** [comment]
Ok, check about source.changes to see if is possible to use it with an electron app

**Comment by angrykoala** [comment]
Closed due to inactivity
