### ISSUE TITLE
Improve logo

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#224]
The current logo (sources in `/resources/logos`) may be improved.

If anyone has ideas/design concepts or improvements, those are welcome

**Comment by angrykoala** [comment]
Keep in mind that the logo is based on a [mate](https://en.wikipedia.org/wiki/Mate_(beverage)

**Comment by juanluischaurant** [comment]
I got this one!

**Comment by angrykoala** [comment]
@juanluischaurant Perfect, please, post any progress here so we can discuss the different ideas and options

**Comment by juanluischaurant** [comment]
@angrykola Okay, I'll be posting here some ideas.

**Comment by juanluischaurant** [comment]
Okay, something here:

I think this logo is actually a masterpiece (seriously), thus, I just did minor modifications to it.
Trying to not affect its awesomeness.

In my version, mainly, you can appreciate that:

* The "G" letter is in another position, to play a bit with the perspective.
* And the strokes for the "pitillo" is smoother.

![gaucho-01](https://user-images.githubusercontent.com/27299983/32064199-2e6b955e-ba47-11e7-834b-00a600352dca.png)
![gaucho-transparent-01](https://user-images.githubusercontent.com/27299983/32064200-2ee97f6e-ba47-11e7-930f-0b3216dd0217.png)

**Comment by angrykoala** [comment]
Nice, I like these changes, please feel free to do a pr updating the current logo.

any other idea that may be an improvement? @juanluischaurant

**Comment by juanluischaurant** [comment]
Thanks, @angrykoala, I would like to check the app's UX/UI in the next few days,
I will open an issue if I find something, in general the project looks good.

**Comment by angrykoala** [comment]
perfect, thanks. there is room for improvements on that, currently there are 2 related issues #173 #177

**Comment by angrykoala** [comment]
I don't see anyone come up with new ideas, so I'll close this issue as the changes made by @juanluischaurant improved the logo
