### ISSUE TITLE
Wiki correction about compile process troubleshooting

### ISSUE THREAD

**Issue by aledomu** [angrykoala/gaucho#232]
In the section about common issues when building, the problem described for deb package building is common across all Linux targets. Also, those are problems not specific to this project, so you could as well redirect here so you don't have to document each new target that is added: <https://github.com/electron-userland/electron-builder/blob/master/docs/multi-platform-build.md#linux>

**Comment by angrykoala** [comment]
Thanks for warning. Please, feel free to change the wiki

**Comment by angrykoala** [comment]
Hi @aledomu , While adding the link to electron-builder is a great idea, I had to revert your changes, as I think is worth maintaining the issues and fixes we are finding directly in the wiki, as it will make easier for developers to fix them
