### ISSUE TITLE
Allow to execute various instances of the same task?

### ISSUE THREAD

**Issue by grg121** [angrykoala/gaucho#234]
For example, if I have a tasks which open a terminal with one determined shell and execute some comands/scripts like 'source virtualenvX' or 'cd some/deeep/directory' and I want to open a few of these terminals actually I have to manually duplicate the task and have two or more identical tasks.

That makes me think that we should add an option to duplicate tasks (which would be ugly because you would have various instances of the same tasks) or, better, allow the user to mark a tasks as 'instanciable' so that tasks could be launched two or more times.

I see it in this way: when a user launch a instanciable tasks, the tasks card add a new row with the buttom 'run' and keept the previous row with the 'stop' buttom. Also it sould mark each instance with an identifier.

What do you think?

**Comment by angrykoala** [comment]
While this idea makes sense. I feel it heavily complicates the usage of gaucho. I want to keep it as simple as possible.

Adding a multiple instantiable task will require either multiple states or, as you suggest, the generation of extra temporal tasks.

If you think this is a reasonable usage case, would a "duplicate" option in the context menu defined at #26 solve this problem?
I think is reasonable to duplicate & run tasks if someone want to easily have multiple similar tasks. What do you think?

**Comment by grg121** [comment]
Maybe it could be better to just add the option to duplicate tasks, is simpler as you said and is probable that people do not need it usually, so, yes, I think it would be ok just to allow users to duplicate tasks :)

**Comment by angrykoala** [comment]
Good, duplicate issue created #242 , currently depending on #26
