### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#239]
Would it make sense to provide support for arm machines (e.g. raspberry pi)?

**Comment by aledomu** [comment]
ARM platform is a bit tricky, so I don't recommend to support it officially yet.

**Comment by angrykoala** [comment]
Could it be an `experimental` feature in a separate task?

**Comment by aledomu** [comment]
The problem is that we don't have testers (I think), but yeah, could be made in a separate branch. I suggest to do it after final 0.4 release.

**Comment by angrykoala** [comment]
What do you mean with testers?

**Comment by aledomu** [comment]
Beta testers, people who can test if it works. In my case I don't have any hardware where I can run Linux that runs ARM.

**Comment by angrykoala** [comment]
I have a raspberry pi where I can test that (anyway, we don't really have testers of anything, just people that complains when the shit hits the fan)

The idea behind this issue is just to add the required config and a npm script so anyone can make their own build, but I wasn't planning on releasing or officially supporting ARM architecture, at least for now

**Comment by aledomu** [comment]
That can be done specifying the necessary arguments to the `dist` script. That was another reason why I made it that way.

**Comment by angrykoala** [comment]
No further config needed?

**Comment by aledomu** [comment]
Nope, just `npm run dist -- --armv7l`.

**Comment by angrykoala** [comment]
Could you please add that to the docs?. I'll close this issue then
