### ISSUE TITLE
Config menu behavior and performance improvements

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#240]
When pressing `esc` the modal closes without reverting changes.

Using the `complete` callback (http://materializecss.com/modals.html) it would be possible to easily fix this problem, and improve the code made for #237 (calling onClose in several use cases)

With this, it may be possible as well to stop rendering the config menu with a vue `v-if`, slightly improving the performance

**Comment by rkomiyama** [comment]
Couldn't we remove the `SAVE` button and just keep the `CLOSE` button? This way it's implied that any config changes made are immediately saved and taken into effect.

I also feel like an `X` close icon on the top right corner would be more intuitive for the user.

**Comment by angrykoala** [comment]
Well, I'm not sure if your suggestion fits in this issue, I think it may sense tho remove the save button, as almost anything else in gaucho works without "saving".
However, I'm not sure about the X (it would be close to the X in the app itself) it should be well designed to avoid confusion to the user

**Comment by angrykoala** [comment]
No longer relevant
