### ISSUE TITLE
Add test option for Windows and replace current installer

### ISSUE THREAD

**Issue by aledomu** [angrykoala/gaucho#241]
Does the issue described in the wiki about running tests in Windows just happen sometimes or always?
About the installer, I suggest to replace nsis with squirrel, since in Linux it doesn't need the kludge that is Wine.

**Comment by angrykoala** [comment]
1. I'm not sure to be honest, I think is related to the new version of mocha or something. I know tests in windows were running up to some time ago, I didn't experienced that issue myself, so I'm not sure if it is continuous. If someone is experiencing the issue continuously, we could open a new issue to investigate and fix it (either by using an option that works on every platform or adding a bit of logic to automatically run the tests accordingly to the platform if possible) I would like to avoid having a separate script.
2. Squirrel requires further implementation in the application itself. While it may be cool to have squirrel support in the future, currently it is not a priority as it is not supported in Linux

To be honest, I do not really care about having some tight requirements when executing `dist` as it is intended to be something to be executed only in releases (and, in particular, by me), I though on using specific versions scripts (e.g. dist-linux) or using parameters to allow people to generate a build for their specific system (so, someone in Linux doesn't have to compile to windows if they just want a .deb package for themselves). Keep in mind that gaucho in its latest version is still completely usable without actually building anything, just as a node package.

A good improvement would be using a automated building system (I think travis can be used for that), so the artifacts will be generated in a machine automatically, but I don't know how to configure it (or how it is best to be configured anyway)


I'm going to close this issue, as the problems and issues you are describing seem minor to me (for now), and the fixes are not trivial
