### ISSUE TITLE
When reordering tasks into a new suite, 2 tasks may have the same name

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#244]
By design, 2 tasks in the same suite should **not** have the same name. If the user tries to create a new task with the same name, a number (`(2)`, `(3)`....) will be appended. To do this duplicated are detected after creating a new task

However, adding a new task with the same name in a different suite is valid, so moving that task to the same suite the first task is will result in 2 tasks with the same name in the same suite.

The "Duplicate name" check should be done also whenever a task is added to a suite (either a new task or a moved taks)

**Comment by Trevormichael** [comment]
I got this
