### ISSUE TITLE
Make spectron tests headless

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#253]
Investigate if is possible to run the GUI tests without an actual browser window appearing. This should make testing faster

**Comment by angrykoala** [comment]
related to #105

**Comment by rkomiyama** [comment]
I'm not sure if this is possible, since the intention is to test the application using ChromeDriver/WebDriverIO.

However, if we are truly concerned about how long the Spectron tests take, we could reduce the amount of instances where the app closes and re-opens by condensing the test cases. With that being said, the current tests don't take up that much time.

**Comment by angrykoala** [comment]
1. I'm not sure if it is possible either, but I'm aware of other graphical testing tools that allow headless (or however are called) tests
2. I don't think that's a good idea, as we are making tests cases depend on each other. Maybe it is possible to re-use a sigle instance (created on `before` and removed on `after`)
3. No, not now, but basically we only have 2 tests. When we start creating more of these tests it will take considerably longer

**Comment by rkomiyama** [comment]
Depending on the OS, minimized browsers have limited memory access. This is probably something we need to keep in mind for this issue.

**Comment by angrykoala** [comment]
Well, I know of the existence of headless browsers such as phantom (not the same as minified). Ideally, this is what we should use. Again, i'm not sure it is supported by spectron

**Comment by rkomiyama** [comment]
Maybe we could use this: https://github.com/juliangruber/tape-run

**Comment by angrykoala** [comment]
Well, spectron is a specifically designed tool for electron, I wouldn't change that, just make sure that spectron doesn't support headless tests

**Comment by angrykoala** [comment]
Doesn't seem to be easy/possible, I will close this issue for now
