### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#26]
right-click button should display a context menu with options

**Comment by angrykoala** [comment]
This package could be useful: https://github.com/sindresorhus/electron-context-menu

**Comment by ssteuteville** [comment]
I'm interested. What should the options be to start?

**Comment by angrykoala** [comment]
Well, we could start simple and start integrating new things afterwards, so, for example:
* **About**: Will open the about menu, this option appears at the bottom everywhere you click
* **Toggle Edit**: Will get you in edit mode (or out of it), this option appear everywhere
* **Run/Stop**: Will run/stop the task, this option will **only** appear when clicking on top of an app (if possible, make Run/Stop option change accordingly) and while **not** in edit mode

What do you think for a start? If you see these options are too many to begin with, I'm happy to separate some of them in a different issue afterwards.

If you have any ideas, feel free to comment and implement them as well

Remember that these options should be relatively easy to modify or add new ones

**Comment by ssteuteville** [comment]
Ok cool, I think I could get something like that put together in a few days. Assign, please.

**Comment by angrykoala** [comment]
I can't assign issues to people who are not direct colaborators, anyway, your comment should be enough, consider yourself assigned.

If you need some help, or have something working event without all the features, just comment or PR

**Comment by ssteuteville** [comment]
Having some trouble with this. I tried the library you suggested but I haven't figured out how to get it to have a different context based on what you right clicked.. I've also tried vue-context-click, but it's not handling clicks properly for some reason. Starting to think this one might be too involved for me if I can't get one of these libraries working.

**Comment by angrykoala** [comment]
Hi @ssteuteville , Indeed, I tried the electron-context-menu library and it doesn't seem to support custom context menus depending on class.

If there is no built-in library for this, a possible solution is either to use bare electron or creating an html-css context menu. Both these options require considerable more work and investigation, so if you prefer to check other issues that are simpler it's ok

thanks for your help with this, I'll check another options and come back to this issue

**Comment by angrykoala** [comment]
Here there is a working example of an html-based context menu, may be of help:
http://qnimate.com/customizing-right-click-in-html-page/

**Comment by ssteuteville** [comment]
I'll take another stab at this. I'm using this as a learning exercise for vue and electron and also I want the hacktoberfest shirt -- so my skills in those areas are sub par.

If I can't get this done in a few hours I'll prob switch to a less involved task. I'll try again tonight!

**Comment by angrykoala** [comment]
Don't worry, there are several tasks to start working on gaucho :+1:

**Comment by ssteuteville** [comment]
So, I created a pull request. Seems like something weird is going on with draggable functionality making this harder than it should be. Any advice is appreciated.

**Comment by angrykoala** [comment]
Hi @ssteuteville , that was fast

What do you mean individual menu items? I checked your version and it seems to open on tasks correctly.

For what you explain in the PR, the problem is probably caused by one of the several `ev.prevenDefault` and `ev.stopPropagation` that are in the code.

I used these methods as a way of capturing events and avoid firing other unwanted effects. Maybe those need some tweaking.

I don't think is the dragabble library, as it should be fired with the left-click

Again, point me to the problem, as I can see the menu with "run" so I can't reproduce the problem you described

**Comment by ssteuteville** [comment]
Hey @angrykoala 

The problem isn't that the menu won't open, the problem is that when I click the 'run' option, the click handler on that element never runs. If it did I would see 123 in the console.

I was thinking it was a preventDefault or a stopPropagation as well, I'll start looking for some of them to turn off for debugging. However, I was hoping you might have an idea as to which part of the code is firing a click event other than mine because when I click "run" some click event is firing and causing:

> When I click the item in the list I notice the task_card's li is getting the class, "sortable-chosen" and the style "will-change: transform".

I suspect that whatever code is doing that is where I need to adjust the default behavior and/or propagation.

**Comment by angrykoala** [comment]
Let me check and see if I come up with any ideas

**Comment by ssteuteville** [comment]
Good idea! I'll try that again tonight when I have some free time

**Comment by ssteuteville** [comment]
hey put some more code up in a PR for you to look at. It still isn't done but please read the description on PR.

The issue I described earlier is definitely being caused by vuedraggable library but I came up with what I think is a decent work around.
