### ISSUE TITLE
Menu should be tabable

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#261]
The dropdown menu tabs only work sometimes

**Comment by rkomiyama** [comment]
Could you demonstrate the issue using LICEcap? LICEcap allows you to record your screen and save it as a GIF so you can post it in the GitHub comments. I'm just not entirely sure what the issue is.

**Comment by angrykoala** [comment]
Steps to reproduce:
1. Open gaucho
2. open the side menu
3. Hit tab
You'll see the configuration menu highlighted to select, the others won't highlight hitting tab more times.

The desired behavior is that hitting tab once will highlight the first item, hitting again will highlight the second and so on.

Also the highlighted style may be improved instead of the yellow outline

**Comment by rkomiyama** [comment]
I'm just confused as to why this functionality needs to be put in place when the side menu is not tabbable to begin with.

**Comment by angrykoala** [comment]
Well, the idea is to make it tabbable

**Comment by rkomiyama** [comment]
Okay, I'll look into making the side menu tabbable.

**Comment by angrykoala** [comment]
Thanks
