### ISSUE TITLE
Add New Task Missing After 8 Tasks

### ISSUE THREAD

**Issue by bgordley** [angrykoala/gaucho#265]
When creating more than 8 tasks in a suite, the "Add New Task" button no longer appears.

I am using Windows 10, Gaucho version 0.4

As you can see below, I am in edit mode and do not see the "Add New Task" button.
![image](https://user-images.githubusercontent.com/7117601/33145289-b4515a40-cf74-11e7-8639-a48ef1476da9.png)

**Comment by angrykoala** [comment]
Yeah, this is intentional, as 10 is the maximum amount of tasks per suite set (maybe I should add that in the docs)

Do you really need to add more tasks to a single suite? It may be worth a discussion about adding a configurable limit or removing it completely

**Comment by bryangordley** [comment]
Hello @angrykoala,

My current use case has many steps as I plan to use this as a production utility. Out of curiosity, what would be the purpose of capping the maximum amount of tasks in a suite?

**Comment by angrykoala** [comment]
Too many tasks may have performance and UX issues (having to scroll through the tasks). Initially this was a simple cap as Gaucho was designed to only have 4 or 5 tasks per view (based on my own use) so I decided to add a limit. Being 8 is just and arbitrary limit. In fact, the limit of suites and tasks is defined [here](https://github.com/angrykoala/gaucho/blob/master/app/renderer/app_status.js) as it was intended to be configurable.

I'll try to increase the limit or make it configurable as soon as I can, but I'm happy to accept PRs regarding this issue as well

**Comment by bryangordley** [comment]
Absolutely makes sense. Thank you for the quick response! My team is enjoying this tool quite a bit.

**Comment by angrykoala** [comment]
No problem, I'll figure out some improvement on this area. How many tasks do you reckon you'll be using? (to have an idea about a better upper limit)

**Comment by bryangordley** [comment]
I was thinking around 15 - 20 max. Take a look at my fork if you have some time. I added a range component that has min/max controlled in app_setup. The actual values are moved to the config. I am not sure if this is the best approach or not.

**Comment by angrykoala** [comment]
Please, when your feature is ready for review, do a PR so I can easily review it and point it suggestions or improvements
