### ISSUE TITLE
Create a Flatpak package

### ISSUE THREAD

**Issue by JuanjoSalvador** [angrykoala/gaucho#290]
I'm building a flatpak package for Gaucho that will be available at Flathub.

This is not an issue itself, it's a notice. News will come soon.

**Comment by angrykoala** [comment]
Cool, is this omething that can be integrated automatically into electron-builder process?

**Comment by JuanjoSalvador** [comment]
No, it needs to be created separately. But I guess we can automate the process.

**Comment by angrykoala** [comment]
Closed due to inactivity
