### ISSUE TITLE
Adding a sheduler / automated trigger

### ISSUE THREAD

**Issue by hariharan618** [angrykoala/gaucho#322]
Currently the suite is good , shows results after we open the application and click Run Suite, instead if there's an option to shedule it like the windows task sheduler and let it run in the background, it will be awesome. Loving the UI. Thanks

**Comment by angrykoala** [comment]
Hi hariharan618, would a feature such as "Run Task/Suite in x minutes" while having gaucho running be ok?

**Comment by angrykoala** [comment]
Basic trigger already working on dev branch, thing left to do:
* Trigger for a whole suite
* Reuse running timer to display time left for the task to launch, this may require some refactor on how the task timer works

**Comment by angrykoala** [comment]
Basic scheduling for tasks and suites added, pending for release on 0.5.4
