### ISSUE TITLE
SweetAlert2: Unknown parameter "type" warning message

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#364]
SweetAlert2: Unknown parameter "type"

**Comment by mukhusin** [comment]
what is the solution of SweetAlert2: Unknown parameter "type"

**Comment by angrykoala** [comment]
Hi @mukhusin  This was an internal problem that should be fixed (tbh, I don't even remember exactly why, cause I didn't bother to explain in detail, sorry)

If you are experiencing this issue or a similar problem:
1. Make sure you are running the last version of Gaucho (0.10.2) - You can download it here: https://github.com/angrykoala/gaucho/releases/tag/0.10.2
2. If the problem persist, please open a new issue with a description of your problem (OS version, gaucho version, and problem, with screenshots if possible) and we can discuss the solution there :smiley:

**Comment by mukhusin** [comment]
@angrykoala I solved it, The problem was because I used 
``swal({ ..... })`` instead of ``swal.fire({ ..... })``
![swal](https://user-images.githubusercontent.com/31729456/115985724-cbb17380-a5b5-11eb-9a5f-ae89a809d2d5.PNG)
![swalFire](https://user-images.githubusercontent.com/31729456/115985734-e4ba2480-a5b5-11eb-9a16-64f8ffe6ef6e.PNG)

**Comment by Sanyukta217** [comment]
From version 9 of sweetalert2, the **type** property has been changed to **icon**. 
Swal.fire({
    icon: 'warning',
    title: 'Heading of swal',
    text: 'warning swal'
  });

**Comment by mukhusin** [comment]
Ok thanks

**Comment by snithfferx** [comment]
I got this message trying as your npm example.

"No overload matches this call.
  Overload 1 of 2, '(options: SweetAlertOptions): Promise<SweetAlertResult<any>>', gave the following error.
    Type 'string' is not assignable to type 'SweetAlertIcon | undefined'.
  Overload 2 of 2, '(title?: string | undefined, html?: string | undefined, icon?: SweetAlertIcon | undefined): Promise<SweetAlertResult<any>>', gave the following error.
    Argument of type '{ title: string; text: string; icon: string; }' is not assignable to parameter of type 'string'.ts(2769)"

this is how I did inside my ts file:
```javscript
function` alerta (message:string, title:string ='Atention', type:string = 'info') {
    Swal.fire({
        title:title, 
        text:message, 
        icon:type
    });
}
```
Or is only can use as a imported library in the html on client side?
If I do this same function in my html importing the library as <script src=""> all works fine.
