### ISSUE TITLE
Remove/Change timer icon

### ISSUE THREAD

**Issue by badrelmers** [angrykoala/gaucho#387]
Hi,
when I schedule a task , an icon appear in the place where the exit return should appear
![image](https://user-images.githubusercontent.com/40046489/80929187-66a7b100-8d99-11ea-8026-612a5ce1c5a6.png)
so if a task fails I will not know, because the timer icon will always take the place of the error icon 
![image](https://user-images.githubusercontent.com/40046489/80929217-a7072f00-8d99-11ea-8dc4-86eac7d4b47e.png)

this is how it looks a failing scheduled task:
![image](https://user-images.githubusercontent.com/40046489/80929255-e6358000-8d99-11ea-93f5-7b75b61eabe7.png)

is it possible to remove the timer icon? because we already have the time countdown, it is sufficient so we do not need an icon to tell us there is a timer in work. 
or maybe to have two columns one for the exit return and one for the scheduling policy.

thank you very much

**Comment by angrykoala** [comment]
I understand your are having this problem when scheduling a task on repeat.

I'll need to review this request with some time, but it may be reasonable to change the icon, so it shows both the status of last execution and the fact that it is scheduled

**Comment by angrykoala** [comment]
@badrelmers 
Sorry for taking too long, this issue is solved and will be published soon in v0.9.1 or v0.10.0
