### ISSUE TITLE
missing npm dependency after snap install

### ISSUE THREAD

**Issue by Paplewski** [angrykoala/gaucho#407]
After installing the program (via ubuntu store) and running task timer program crashes because of missing `npm`:

![image](https://user-images.githubusercontent.com/28847593/110352578-62da6000-8036-11eb-9f6f-85dfba7af5e5.png)

**Comment by angrykoala** [comment]
Hi @Paplewski 
I'm not sure if I understand your problem, but the "Install" task is just an example and it is normal that fails (I created the issue #408 to address this and create more clear examples). Your gaucho should be ready to run.

Please, create your own tasks and try those (you can follow [this instructions](https://github.com/angrykoala/gaucho/wiki/Using-Gaucho#creating-and-editing-tasks)).


I'll close this issue (if you are still having troubles, need more help, or I didn't understand your issue, please feel free to comment here). If your task also fails, please send me a screenshot of the configuration of the task (like the image below)

![Screenshot from 2021-03-08 22-47-44](https://user-images.githubusercontent.com/5960567/110386339-71d60800-8060-11eb-8fe5-fae636baaa6e.png)
