### ISSUE TITLE
Move check for updates setting out of display section

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#426]
In settings, the "Check For Updates" option is in "Display" section. Which doesn't make sense. Either move it to a different section or out of the sections entirely.

Updating the docs required as well

**Comment by shub78910** [comment]
Hey, sorry man, I thought vue would be similar to react and i can make changes, but that's not the case.
Thanks though!

**Comment by lucasrcdias** [comment]
@angrykoala Could you assign me to this issue?

**Comment by angrykoala** [comment]
All yours @lucasrcdias thanks!
