### ISSUE TITLE
Copy command option in context menu

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#428]
Right click on a task -> "Copy Command" to copy the task command contents to the clipboard. This way, task can quickly be run in a different terminal without having to go into edit mode

**Comment by amimaro** [comment]
I need some help at the tests.
In which file should I put the testing for the right-click menu?
Also ```npm run test``` is failing at "Stop task", can I ignore it for the PR?

**Comment by angrykoala** [comment]
Tests are way more flaky than I would like to, and it needs a whole rework, so don't worry too much about them.
If you are able to test your new feature, feel free to add it wherever you feel is appropriate within the tests/ folder. You can create a PR and discuss details of where to put it in there. If the tests was already failing in master, you can ignore it.

**Comment by amimaro** [comment]
OS: Windows10
Node: v14.16.0
NPM: 6.14.11

Here is the response:

![image](https://user-images.githubusercontent.com/6666978/137310493-0455374c-f262-4d2c-be2a-2dd242b50e18.png)
