### ISSUE TITLE
Test (and add) icon on Mac

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#56]
Currently, the gaucho icon #11 is working on Ubuntu and Windows. Test in a mac system, if it isn't working (probably it won't) add it

**Comment by angrykoala** [comment]
Someone with a mac to test this?

**Comment by panvourtsis** [comment]
i am running it on mac just fine

**Comment by angrykoala** [comment]
Thanks, could you follow the next steps to debug this and (hopefully) close the issue:

`npm run build-electron` should generate a folder `builds/` with the production version of gaucho (the files to be distributed along users). This version should be installable/executable (tbh I'm not sure how it works on mac). If you can, please check that the behavior when executed that version is the expected for a mac user, particularly if the icon is properly displayed everywhere.
