### ISSUE TITLE
Support rearranging tasks

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/gaucho#87]
It should be possible to rearrange tasks, so the order of the tabs can be changed or moved to a different suite

**Comment by panvourtsis** [comment]
thinking about something like sortablejs ?

**Comment by angrykoala** [comment]
The main difficulty here is making whatever we use work with materializecss collapsibles (http://materializecss.com/collapsible.html), each task card should have a icon or something as the drag area to move the cards around.

If this is not possible (maybe collapsible makes it very hard or something) we could simply use a couple of arrow buttons to move the tasks when edit mode is on

**Comment by panvourtsis** [comment]
i can start implementing the arrows and also investigate to see if its possible to d&d if not we will stick with arrows

**Comment by angrykoala** [comment]
Looks like a plan, thanks!

The moving around may be a bit tricky, check the code for deleting tasks, as it contains all the logic to move tasks around as well
