### ISSUE TITLE
Error with windows path

### ISSUE THREAD

**Issue by dvgamer** [angrykoala/gaucho#96]
![image](https://cloud.githubusercontent.com/assets/10203425/25471782/c62bb3bc-2b52-11e7-83bf-b2e90b13c590.png)

please fixed:
1. what name " 2" append after save again. (check issue #97 for this)
2.  why cannot start with that path.

**Comment by angrykoala** [comment]
Hi @dvgamer, problem 1 is confirmed and will be fixed soon (more updates in the issue #97). Please, indicate the steps to reproduce the second problem (with the path).
What is the configuration of the task? (command and path)

**Comment by angrykoala** [comment]
This issue renamed to be specific to the second problem, first problem can be found at #97
